# Generated by Django 2.0.6 on 2018-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('url', models.TextField(default='', verbose_name='请求url')),
                ('method', models.TextField(default='', verbose_name='请求方法')),
                ('par_type', models.TextField(default='', verbose_name='参数类型')),
                ('headers', models.TextField(default='', verbose_name='header')),
                ('parameter', models.TextField(default='', verbose_name='参数')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
