# Generated by Django 2.0.6 on 2018-11-10 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181108_2301'),
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='method',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='parameter',
        ),
        migrations.AddField(
            model_name='testcase',
            name='moudle',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='project_app.Module', verbose_name='所属项目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='req_headers',
            field=models.TextField(default='', verbose_name='header'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='req_method',
            field=models.TextField(default='', verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='req_parameter',
            field=models.TextField(default='', verbose_name='参数'),
        ),
    ]
