# Generated by Django 2.1.1 on 2018-11-29 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_testtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtask',
            old_name='par_type',
            new_name='describe',
        ),
    ]
