# Generated by Django 2.0.6 on 2018-11-10 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181108_2301'),
        ('interface_app', '0003_auto_20181110_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='moudle',
        ),
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='project_app.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='req_assert',
            field=models.TextField(default='', verbose_name='验证'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='par_type',
            field=models.CharField(default='', max_length=10, verbose_name='参数类型'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='req_headers',
            field=models.TextField(default='', verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='req_method',
            field=models.CharField(default='', max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='req_parameter',
            field=models.TextField(default='', verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.TextField(default='', verbose_name='请求url'),
        ),
    ]
